MEDICARE_PART_D_PROVIDER_OFF_SET_START = """SELECT COUNT(*) FROM SOCRATA.MEDLY.MEDICARE_PART_D_PROVIDER"""

MEDICARE_PART_D_PROVIDER_OFF_SET_END = """https://data.cms.gov/resource/77gb-8z53.csv?$select=count(*)"""

# MEDICARE_PART_D_PROVIDER_OFF_SET_END = """
# curl --output --header "X-App-Token: xEtrPUl5zQnaVVS3OfQhZCF2X" -X GET  'https://data.cms.gov/resource/77gb-8z53.csv?$select=count(*)' 
# | grep -w '\d\d*' | tr -d "\"" | xargs
# """

MEDICARE_PART_D_PROVIDER_TABLE_MAX_NPI = """    
SELECT MAX(TRY_TO_NUMBER(TRIM(REGEXP_REPLACE(NPI,'\\"|\\""','')))) AS NPI
FROM SOCRATA.MEDLY.MEDICARE_PART_D_PROVIDER
"""

# -Z --parallel-max 5
MEDICARE_PART_D_PROVIDER_FILE_MAX_NPI = """
curl --output --header "X-App-Token: xEtrPUl5zQnaVVS3OfQhZCF2X" -X GET  'https://data.cms.gov/resource/77gb-8z53.csv?$select=max(npi)' | grep -w '\d\d*' | tr -d "\"" | xargs
"""
MEDICARE_PART_D_PROVIDER_DOWNLOAD_FILE = """
curl --silent  "X-App-Token: chycbaw39ixmuyybrqu0cdyzw" -X GET 'https://data.cms.gov/resource/77gb-8z53.csv?$order=%27npi%27&$where=npi%20%3E%20%271951128297%27&$offset=[1-50000:5000]&$limit=5000' > 'medical_provider_payment.csv'
"""

MEDICARE_PART_D_PROVIDER_TRUNCATE_STAGE = """
TRUNCATE TABLE SOCRATA.STAGE.MEDICARE_PART_D_PROVIDER
"""

MEDICARE_PART_D_PROVIDER_COPY_TO_STAGE = """
COPY INTO SOCRATA.STAGE.MEDICARE_PART_D_PROVIDER 
FROM @SOCRATA.STAGE.tool_stage 
FILE_FORMAT=(COMPRESSION = AUTO)
ON_ERROR=CONTINUE
"""

MEDICARE_PART_D_PROVIDER_LOAD_MASTER_TABLE = """
INSERT INTO SOCRATA.MEDLY.MEDICARE_PART_D_PROVIDER 
SELECT *
FROM SOCRATA.STAGE.MEDICARE_PART_D_PROVIDER
ORDER BY NPI"""

MEDICARE_PART_D_PROVIDER_LOAD_CREATE_VIEW = """
CREATE OR REPLACE VIEW SOCRATA.PUBLIC.VW_MEDICARE_PART_D_PROVIDER AS
SELECT NPI, NPPES_PROVIDER_STATE, SPECIALTY_DESC, DESCRIPTION_FLAG, DRUG_NAME, GENERIC_NAME, BENE_COUNT, TOTAL_CLAIM_COUNT, TOTAL_30_DAY_FILL_COUNT, TOTAL_DAY_SUPPLY, TOTAL_DRUG_COST, TOTAL_DRUG_COST_GE65
FROM SOCRATA.STAGE.MEDICARE_PART_D_PROVIDER
ORDER BY NPI """

MEDICARE_PART_D_PROVIDER_UPDATE_JOB_HISTORY_METADATA = """
INSERT INTO METADATA.JOB_HISTORY(DATASET_ID,JOB_ID,START_DATE,JOB_NAME,START_TIME,END_DATE,ELAPSED_TIME,OFFSET_START,OFFSET_END, POST_JOB_MAX_TABLE_COUNT,JOB_STATUS)
VALUES({DATASET_ID},{JOB_ID},{START_DATE},{JOB_NAME},{START_TIME},{END_DATE},{ELAPSED_TIME},{OFFSET_START},{OFFSET_END}
{POST_JOB_MAX}_{TABLE_COUNT},{JOB_STATUS})
"""
