CREATE VIEW SOCRATA.PUBLIC.VW_MEDICARE_PART_D_PROVIDER AS
SELECT 	NPI, 
	NPPES_PROVIDER_STATE, 
	SPECIALTY_DESC, 
	DESCRIPTION_FLAG, 
	DRUG_NAME, 
	GENERIC_NAME, 
	BENE_COUNT, 
	TOTAL_CLAIM_COUNT, 
	TOTAL_30_DAY_FILL_COUNT, 
	TOTAL_DAY_SUPPLY, 
	TOTAL_DRUG_COST, 
	TOTAL_DRUG_COST_GE65
FROM SOCRATA.MEDLY.MEDICARE_PART_D_PROVIDER
ORDER BY NPI; 


