
CREATE OR REPLACE TABLE SOCRATA.MEDLY.MEDICARE_PART_D_PROVIDER (
    NPI TEXT,
    NPPES_PROVIDER_LAST_ORG_NAME TEXT,
    NPPES_PROVIDER_FIRST_NAME TEXT,
    NPPES_PROVIDER_CITY TEXT,
    NPPES_PROVIDER_STATE TEXT,
    SPECIALTY_DESC TEXT,
    DESCRIPTION_FLAG TEXT,
    DRUG_NAME TEXT,
    GENERIC_NAME TEXT,  
    BENE_COUNT NUMBER,
    TOTAL_CLAIM_COUNT  NUMBER,
    TOTAL_30_DAY_FILL_COUNT NUMBER,
    TOTAL_DAY_SUPPLY NUMBER,
    TOTAL_DRUG_COST NUMBER,
    BENE_COUNT_GE65 NUMBER,  
    BENE_COUNT_GE65_SUPPRESS_FLAG TEXT,
    TOTAL_CLAIM_COUNT_GE65 NUMBER,
    GE65_SUPPRESS_FLAG TEXT,
    TOTAL_30_DAY_FILL_COUNT_GE65 NUMBER,
    TOTAL_DAY_SUPPLY_GE65 NUMBER,
    TOTAL_DRUG_COST_GE65 NUMBER
);
